# Site settings
title: Jinke He
email: jinkehe1996@gmail.com
email2: J.He-4@tudelft.nl
description: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jinkehe.github.io/" # the base hostname & protocol for your site
twitter_username: jinke_he 
github_username:  JINKEHE
linkedin_username: jinke-he

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Master student at University of Oxford"
excerpt_separator: "<!--more-->"

includes:
- assets

# collections:
# - news

future: true
# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
