# Site settings
title: Jinke He
email: jinkehe1996@gmail.com
description: > # this means to ignore newlines until "baseurl:"
These violent delights have violent ends.
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jinkehe.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  JINKEHE

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Master student at University of Oxford"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
